language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'node-generator-jingle' ]; then cd .. && eval "mv $currentfolder node-generator-jingle" && cd node-generator-jingle; fi


